### ISSUE TITLE
实践中的两点小细节

### ISSUE THREAD

**Issue by RenjunLai** [myhsia/hduthesis#1]
模板中调用的Songti SC、Heiti SC字体为mac系统自带字体，在win下可能存在编译问题，可能需要手动替换为SimSun、SimHei（win自带字体）。
另：计算机学院发25年标准及本工程参考的22年教务处标准中引用格式要求为“参考文献书写格式应符合GB7714-1987《文后参考文献著录规则》。”
而在layout中的配置为:
```
\RequirePackage[sort&compress]{gbt7714}
\bibliographystyle{gbt7714-numerical}
```
经查询，工程使用的gbt7714宏包没有提供1987版本能力，其默认为2015标准。
若使用biblatex-gb7714-2015 宏包，该包（宣称）提供了gb7714-1987能力，未进一步核验。
尽管从规则上讲，在已有新标准情况下旧标准理应废止使用，特别是注意到华南理工大学的模板里出现了相关的激烈讨论，但是在学校教务处没有更新动力的现实情况下可能还是得用这个早已废止的版本。
![Image_160656574577619](https://github.com/user-attachments/assets/164be97f-c10b-4b26-8db3-91410b62994e)

**Comment by RenjunLai** [comment]
且非常戏剧性的是学校发的格式也并不符合GB7714-1987的标号（区别为有无括号包裹）

**Comment by myhsia** [comment]
1. `可能需要手动替换为SimSun、SimHei（win自带字体）` 确实是这样的，用户手册已经明确说明，可通过导言区设置. 这一点相对于其他模板把字体写死，已经很自由了.
2. 参考文献国标标准这一点确实，弄的我也很懊恼 . 目前我正在准备向教务处提一下建议；最近我也在做本科毕业设计，我把我的参考文献格式给导师看了下，导师表示没问题：重点看是否标注了期刊编号、页数等.
3. `非常戏剧性的是学校发的格式也并不符合GB7714-1987的标号` 本人能力（精力）有限，并无时间为此再制作一个 `.bst` 文件. 不过后期会增加一个选项，让用户调用2015或者1987版本.

**Comment by michael-etzkorn** [comment]
在miktex和windows环境下，暂时绕开编译问题的方案：
- 把`tex`目录下的cls文件移动到和`<top>.tex`同一层
- 把`hduthesis-typeset-module.code.tex` 里 `\setmathfont` `\setCJKmainfont``setCJKsansfont`注释掉，使用XeLaTeX默认的字体
  - 如果不给参数，hduthesis包会直接崩掉，所以还需要设上`math-font` `CJKmain-font`   `CJKsans-font`
    -  这个以后去研究，应该支持默认什么都没设  

手动换SimSun Regular SimHei Regular等等都出问题，我暂时不去研究这些字体细节
